bottomsupapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/signup/', views.signup, name='signup'),
    path('about/', views.about, name='about'),
    path('drinks/', views.drinks_index, name='index'),
    path('survey/', views.SurveyForm.as_view(), name='survey_form'),
    path('drinks/generate', views.generate_drink, name='generate_drink'),
    path('drinks/add_drink/', views.add_drink, name='add_drink'),
    path('drinks/<int:drink_id>/', views.drink_detail, name='drink_detail'),
    path('drinks/<int:pk>/delete/', views.DrinkDelete.as_view(), name='drink_delete'),
    path('drinks/<int:drink_id>/assoc_category/<int:category_id>/', views.assoc_category, name="add_category"),
    path('drinks/<int:drink_id>/unassoc_category/<int:category_id>/', views.unassoc_category, name="remove_category"),
    path('drinks/<int:drink_id>/add_photo/', views.add_photo, name='add_photo'),      
    path('photo/<int:pk>/delete/', views.PhotoDelete.as_view(), name='photo_delete'),
    path('categories/', views.CategoryList.as_view(), name="categories_index"),
    path('categories/create/', views.CategoryCreate.as_view(), name="categories_create"),
    path('categories/<int:pk>/', views.CategoryDetail.as_view(), name="categories_detail"),
    path('categories/<int:pk>/update/', views.CategoryUpdate.as_view(), name="categories_update"),
    path('categories/<int:pk>/delete/', views.CategoryDelete.as_view(), name="categories_delete"),
]

main_app/models.py
from statistics import mode
from tabnanny import verbose
from unicodedata import category
from django.db import models
from django.contrib.auth.models import User
from django.forms import CharField
from django.utils import timezone
from django.urls import reverse
# Create your models here.

LIQUORS = (
    ('V', 'Vodka'),
    ('G', 'Gin'),
    ('R', 'Rum'),
    ('T', 'Tequila'),
)

ANSWERS1 = (
    ('W', 'Work'),
    ('P', 'Play'),
)
ANSWERS2 = (
    ('A', 'Adventurous'),
    ('C', 'Classic'),
)
ANSWERS3 = (
    ('P', 'Pick-Me-Up'),
    ('R', 'Relaxation'),
)

class Ingredient(models.Model):
    ingredient_name = models.CharField(max_length=50)
    def __str__(self):
        return f'{self.ingredient_name}'

    class Meta:
        verbose_name = 'ingredient'
        verbose_name_plural = 'ingredients'

class Category(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name 

    class Meta:
        ordering = ['name']
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('categories_index')


class Drink(models.Model):
    drink_id = models.CharField(max_length=10)
    drink_name = models.CharField(max_length=100)
    drink_instructions = models.TextField(max_length=500)
    drink_pic = models.CharField(max_length=100)
    ingredients = models.ManyToManyField(Ingredient)
    users = models.ManyToManyField(User)
    created_date = models.DateTimeField('date created', default=timezone.now)
    categories = models.ManyToManyField(Category)
    def __str__(self):
        return f'{self.drink_name} ({self.drink_id})'


class Survey(models.Model):
    liquor_pref = models.CharField('What is your preferred liquor?',
        max_length=1,
        choices=LIQUORS,
        default=LIQUORS[0][0],
    )
    q1 = models.CharField('Was Today work or play?',
        max_length=1,
        choices=ANSWERS1,
        default=ANSWERS1[0][0],
    )
    q2 = models.CharField('Are you feeling adventurous or classic?',
        max_length=1,
        choices=ANSWERS2,
        default=ANSWERS2[0][0],
    )
    q3 = models.CharField('Do you need a pick-me-up or to relax?',
        max_length=1,
        choices=ANSWERS3,
        default=ANSWERS3[0][0],
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
   
class Photo(models.Model):
  url = models.CharField(max_length=200)
  drink = models.ForeignKey(Drink, on_delete=models.CASCADE)

  def get_absolute_url(self):
        return reverse('drink_details')

  def __str__(self):
    return f'Photo for drink_id: {self.drink_id} @{self.url}'

main_app/views.py
import os 
import boto3
import uuid
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import ANSWERS1, Category, Drink, Ingredient, Survey, Photo
import requests, random 
# Create your views here.

def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

@login_required
def drinks_index(request):
  drinks = Drink.objects.all().order_by('-created_date')
  return render(request, 'drinks/index.html', {'drinks': drinks})

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('/')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

def generate_drink(request):
    ALC_LOOKUP = {'V': 'vodka', 'G': 'gin', 'R': 'rum', 'T': 'tequila'}
    alc_type = ALC_LOOKUP[request.POST['liquor_pref']]
    cocktails_by_ingredient = requests.get(f'https://www.thecocktaildb.com/api/json/v2/9973533/filter.php?i={alc_type}').json()

    all_drinks = cocktails_by_ingredient['drinks']
    index_list = []
    for all_ids in all_drinks:
        ingredient_choice_ids = all_ids['idDrink']
        index_list.append(ingredient_choice_ids) 

    if request.POST['q1'] == ANSWERS1[0][0]:
        cocktails_by_category = requests.get('https://www.thecocktaildb.com/api/json/v2/9973533/filter.php?c=ordinary_drink').json()
    elif request.POST['q1'] == 'P':
        cocktails_by_category = requests.get('https://www.thecocktaildb.com/api/json/v2/9973533/filter.php?c=cocktail').json()

    all_category_drinks = cocktails_by_category['drinks']
    index_list2 = []
    for all_ids in all_category_drinks:
        category_choice_ids = all_ids['idDrink']
        index_list2.append(category_choice_ids) 

    index_list3 = []
    for id in index_list:
      if id in index_list2:
        index_list3.append(id)

    drink_id = random.choice(index_list3)
    print(drink_id)
    final_drink_render = requests.get('https://www.thecocktaildb.com/api/json/v1/1/lookup.php?i=' + drink_id ).json()

    drink_name = final_drink_render['drinks'][0]['strDrink']
    drink_instructions = final_drink_render['drinks'][0]['strInstructions']
    drink_pic = final_drink_render['drinks'][0]['strDrinkThumb']
    drink_ingredient1 = final_drink_render['drinks'][0]['strIngredient1']
    drink_ingredient2 = final_drink_render['drinks'][0]['strIngredient2']
    drink_ingredient3 = final_drink_render['drinks'][0]['strIngredient3']
    drink_ingredient4 = final_drink_render['drinks'][0]['strIngredient4']
    drink_ingredient5 = final_drink_render['drinks'][0]['strIngredient5']
    drink_ingredient6 = final_drink_render['drinks'][0]['strIngredient6']
    drink_ingredient7 = final_drink_render['drinks'][0]['strIngredient7']
    drink_ingredient8 = final_drink_render['drinks'][0]['strIngredient8']
    
    return render(request, 'drinks/todays_cocktail.html', {
        'cocktails_by_ingredient': cocktails_by_ingredient,
        'drink_id': drink_id, 
        'drink_name': drink_name, 
        'drink_instructions': drink_instructions, 
        'drink_pic': drink_pic,
        'drink_ingredient1': drink_ingredient1,
        'drink_ingredient2': drink_ingredient2,
        'drink_ingredient3': drink_ingredient3,
        'drink_ingredient4': drink_ingredient4,
        'drink_ingredient5': drink_ingredient5,
        'drink_ingredient6': drink_ingredient6,
        'drink_ingredient7': drink_ingredient7,
        'drink_ingredient8': drink_ingredient8,
    })

def add_drink(request):
  data = {key: val for key, val in request.POST.items()}
  drink = Drink.objects.filter(drink_id=data['drink_id'])
  if drink:
      drink[0].users.add(request.user)    
      return redirect('index')
  del data['csrfmiddlewaretoken']
  ingredients = []
  for i in range(1,9):
      if data[f'drink_ingredient{i}'] != 'None' and data[f'drink_ingredient{i}'] != '': 
        ingredients.append(data[f'drink_ingredient{i}'])
      del data[f'drink_ingredient{i}'] 
  drink = Drink.objects.create(**data)
  drink.users.add(request.user)
  for ingred in ingredients:
      ingredient = Ingredient.objects.filter(ingredient_name=ingred)
      if not ingredient:
        ingredient = Ingredient.objects.create(ingredient_name=ingred)
      else:
        ingredient = ingredient[0]
      drink.ingredients.add(ingredient)

  return redirect('index')

def drink_detail(request, drink_id):
    drink = Drink.objects.get(id=drink_id)
    ingredients_list = list(drink.ingredients.all().values_list('ingredient_name', flat=True))
    ingredients = str(', '.join(ingredients_list))
    category_ids = drink.categories.all().values_list('id')
    categories = Category.objects.exclude(id__in=category_ids)
    print(ingredients)  
    return render(request, 'drinks/detail.html', {
        'drink': drink, 
        'ingredients' : ingredients,
        'categories' : categories,
    })

# Class-Based View (CBV)
class SurveyForm(LoginRequiredMixin, CreateView):
  model = Survey
  fields = ['liquor_pref', 'q1', 'q2', 'q3']

class DrinkDelete(LoginRequiredMixin, DeleteView):
  model = Drink
  success_url = '/drinks/'

class CategoryList(ListView):
  model = Category

class CategoryDetail(DetailView):
  model = Category

class CategoryCreate(CreateView):
  model = Category
  fields = '__all__'

class CategoryUpdate(UpdateView):
  model = Category
  fields = ['name']

class CategoryDelete(DeleteView):
  model = Category
  success_url =  '/categories/'

def assoc_category(request, drink_id, category_id):
  drink = Drink.objects.get(id=drink_id)
  drink.categories.add(category_id)
  return redirect ('drink_detail', drink_id=drink_id)

def unassoc_category(request, drink_id, category_id):
  drink = Drink.objects.get(id=drink_id)
  drink.categories.remove(category_id)
  return redirect ('drink_detail', drink_id=drink_id)


@login_required
def add_photo(request, drink_id):
  # photo-file wil be the "name" attribute of the input
  photo_file = request.FILES.get('photo-file', None)
  if photo_file:
    s3 = boto3.client('s3')
    # need a unique "key" for s3 
    # need the same file extension as well
    key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
    try: 
      bucket = os.environ['S3_BUCKET']
      s3.upload_fileobj(photo_file, bucket, key)
      # build the full url string
      url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
      Photo.objects.create(url=url, drink_id=drink_id)
    except Exception as e:
      print('An error occurred uploading to S3')
      print(e)
  return redirect('drink_detail', drink_id=drink_id)

class PhotoDelete(DeleteView):
  model = Photo
  success_url = '/drinks/'
  

main_app/templates/main_app/category_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<div class="section">
  <h1 class="grey-text text-darken-3">Delete Category</h1>

  <h4 class="grey-text text-darken-3">Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?
  </h4>

  <form action="" method="POST">
    {% csrf_token %}
    <button class="waves-effect waves-light btn grey darken-3 white-text" type="submit" value="Submit" class="btn">Yes,
      Delete!</button>
    <a class="waves-effect waves-light btn grey darken-3 white-text"
      href="{% url 'categories_detail' object.id %}">Cancel</a>
  </form>
</div>

{% endblock %}

main_app/templates/main_app/category_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="section">
<h1 class="grey-text text-darken-3">Category Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
        <h4 class="card-title grey-text text-darken-1">{{ category.name }}</h4>
    
        {% for drink in category.drink_set.all %}
        <p>Drink: {{ drink.drink_name }}</p>
        {% empty %}
        <p>No Drinks have been added to this category yet</p>
        {% endfor %}

        <a  class="waves-effect waves-light btn grey darken-3 white-text" href="{% url 'categories_delete' category.id %}">Delete</a>
        <a  class="waves-effect waves-light btn grey darken-3 white-text" href="{% url 'categories_update' category.id %}">Edit</a>
      </div>
</div>
</div>
{% endblock %}

main_app/templates/main_app/category_form.html
{% extends 'base.html' %}
{% block content %}

<div class="section">
    {% if object %}
    <h1 class="grey-text text-darken-3">Edit <span>{{object.name}}</span></h1>
    {% else %}
    <h1 class="grey-text text-darken-3">Add Cocktail Category</h1>
    {% endif %}
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button class="waves-effect waves-light btn grey darken-3 white-text" type="submit" value="Submit"
            class="btn">Submit</button>
    </form>
</div>

{% endblock %}

main_app/templates/main_app/category_list.html
{% extends 'base.html' %}
{% block content %}

<div class="container center-align">
    <div class="section">
        <h1 class="grey-text text-darken-3">Category List</h1>
            {% for category in category_list %}
            <div class="card-content white-text">
                <h4 class="card-title grey-text text-darken-1">{{ category }}</h4>
                <form action="{% url 'categories_detail' category.id %}">
                    {% csrf_token %}
                    <button class="waves-effect waves-light btn grey darken-3 white-text" type="submit">Category
                        Details</button>
                </form>

            <h6 class="grey-text text-darken-4"><strong>Cocktails in this category:</strong></h6>
            {% for drink in category.drink_set.all %}
            <h6 class="grey-text text-darken-2">{{ drink.drink_name }}</h6>
            {% empty %}
            <p class="grey-text text-darken-2">No Drinks have been added to this category yet</p>
            {% endfor %}
            <hr>
        </div>
        {% endfor %}
    </div>
</div>
</div>
</div>
{% endblock %}

main_app/templates/main_app/drink_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="section">
  <h1 class="grey-text text-darken-3">Delete Drink</h1>

  <h4 class="grey-text text-darken-3">Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?
  </h4>

  <form action="" method="POST">
    {% csrf_token %}
    <button class="waves-effect waves-light btn grey darken-3 white-text" type="submit" value="Submit" class="btn">Yes,
      Delete!</button>
    <a class="waves-effect waves-light btn grey darken-3 white-text" href="{% url 'drink_detail' drink.id %}">Cancel</a>
  </form>
</div>
{% endblock %}

main_app/templates/main_app/photo_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="section">
  <h1 class="grey-text text-darken-3">Delete Photo</h1>

  <h4 class="grey-text text-darken-3">Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?
</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a class="waves-effect waves-light btn grey darken-3 white-text" href="{% url 'drink_detail' photo.id %}">Cancel</a>
  </form>
</div>
{% endblock %}

main_app/templates/main_app/survey_form.html
{% extends 'base.html' %}
{% block content %}

<div class="section">
  <div class="center-align">
    <img class="circle responsive-img" src="https://i.imgur.com/iAfqXM9.png" alt="">
    <h4 class="grey-text text-darken-1">Welcome to Bottoms Up! Please fill out information about your day below.</h4>
  </div>
  <form class="grey-text text-darken-1" action="{% url 'generate_drink' %}" method="POST">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <div class="section">
      <button class="waves-effect waves-light btn grey darken-3 white-text" type="submit" value="Submit" class="btn">Get
        My Drink!</button>
    </div>
  </form>

  <script>

    const selectEl = document.getElementById('id_liquor_pref');
    M.FormSelect.init(selectEl);
    const selectEl2 = document.getElementById('id_q1');
    M.FormSelect.init(selectEl2);
    const selectEl3 = document.getElementById('id_q2');
    M.FormSelect.init(selectEl3);
    const selectEl4 = document.getElementById('id_q3');
    M.FormSelect.init(selectEl4);

  </script>
</div>

{% endblock %}